### ISSUE TITLE
Zombie nested folders for Namespace Files

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/terraform-provider-kestra#98]
### Feature description

![image](https://github.com/kestra-io/terraform-provider-kestra/assets/86264395/d02edf88-c47f-42dd-9465-c63a11d40f71)

to reproduce, first add this to main.tf, apply, then remove this and reapply - you should see that files are removed, but  folders remain as zombies 🧟 

```terraform
resource "kestra_namespace_file" "prod_scripts" {
  for_each  = fileset(path.module, "scripts/**")
  namespace = "prod"
  filename = "/${each.value}"
  content   = file(each.value)
}
```

repo to reproduce: https://github.com/anna-geller/kestra-ci-cd/blob/main/main.tf

**Comment by brian-mulier-p** [comment]
I'm not a terraform expert but I would say this is due to fileset not returning directory entries so there is no specific CREATE / DELETE calls done on these. Might have to find a way for terraform to list all dir and subdir along files for it to work (or maybe we have to do some hack in kestra provider)

**Comment by brian-mulier-p** [comment]
As discussed, the fix won't work when there is multiple files in a folder that are being deleted by a single tf apply and that the parent folder should be deleted as there is concurrency so none of the delete calls know that it must delete parent folder
